@url=http://localhost:3001/api/auth
@json=Content-Type: application/json

### 获取所有用户信息
# 该接口没有身份验证，直接返回所有用户信息
get {{url}}/users

### 用户注册
# 注册成功
post {{url}}/register
{{json}}

{
    "username": "user1",
    "password": "123456"
}

### 用户注册 - 重复用户名
post {{url}}/register
{{json}}

{
    "username": "user2",
    "password": "123456"
}


### 用户登录
# 登录成功
post {{url}}/login
{{json}}

{
    "username": "user1",
    "password": "123456"
}

###
# 登录失败，用户名错误
post {{url}}/login
{{json}}

{
    "username": "wronguser",
    "password": "123456"
}

### 获取用户资料
# 用户已登录，使用有效的 JWT token
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OWY2YTUzMGIzMDE5NDllMDQyOGY3OSIsImlhdCI6MTczODU0OTU0Nn0.rfM3jcBuLdFM7vWHiysAgcJqjYeCggsNzRziqMvt_2c

###
# 用户未登录，未提供 JWT token
get {{url}}/profile
Authorization: Bearer <invalid-jwt-token>


### Google OAuth - 获取授权
get {{url}}/google


### Google OAuth 回调
# 登录后使用 Google 账号进行登录
get {{url}}/google/callback?code=<authorization-code>
Authorization: Bearer <valid-jwt-token>

